CREATE TABLE AcademyRegistrations (
  id                      INT IDENTITY(1,1) PRIMARY KEY,
  ref_id                  NVARCHAR(20)  NOT NULL UNIQUE,
  student_first_name      NVARCHAR(100) NOT NULL,
  student_last_name       NVARCHAR(100) NOT NULL,
  child_first_name        NVARCHAR(100) NULL,
  child_last_name         NVARCHAR(100) NULL,
  email                   NVARCHAR(200) NOT NULL,
  phone                   NVARCHAR(50)  NULL,
  emergency_contact_name  NVARCHAR(200) NULL,
  emergency_contact_phone NVARCHAR(50)  NULL,
  language                NVARCHAR(5)   NULL,
  level                   NVARCHAR(20)  NULL,
  preferred_teacher       NVARCHAR(200) NULL,
  instrument              NVARCHAR(20)  NULL,
  availabilities          NVARCHAR(MAX) NULL,
  start_preference        NVARCHAR(200) NULL,
  policy_accepted         BIT           NOT NULL DEFAULT 0,
  signature_blob_name     NVARCHAR(500) NULL,
  staff_notes             NVARCHAR(MAX) NULL,
  student_user_id         INT           NULL,
  created_at              DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at              DATETIME2     NULL
);
